export const weatherDescriptions = new Map<number, string>([
  [0, "Clear sky"],
  [1, "Mainly clear"],
  [2, "Partly cloudy"],
  [3, "Overcast"],
  [45, "Fog"],
  [48, "Depositing rime fog"],
  [51, "Drizzle"],
  [53, "Drizzle (moderate)"],
  [55, "Drizzle (dense intensity)"],
  [56, "Freezing Drizzle"],
  [57, "Freezing Drizzle (dense intensity)"],
  [61, "Rain"],
  [63, "Rain (moderate)"],
  [65, "Rain (heavy intensity)"],
  [66, "Freezing Rain"],
  [67, "Freezing Rain (heavy intensity)"],
  [71, "Snow fall"],
  [73, "Snow fall (moderate)"],
  [75, "Snow fall (violent)"],
  [77, "Snow grains"],
  [80, "Rain showers"],
  [81, "Rain showers (moderate)"],
  [82, "Rain showers (violent)"],
  [85, "Snow showers"],
  [86, "Snow showers (heavy)"],
  [95, "Thunderstorm"],
  [96, "Thunderstorm (sight hail)"],
  [99, "Thunderstorm (heavy hail)"],
]);
